services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      args:
        DATABASE_URL: postgres://postgres:postgres@db:5432/mydatabase
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydatabase
      PORT: 3000
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  postgres_data:
