services:
  db:
    image: postgres:13
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    build:
      context: .
      args:
        DATABASE_URL: postgres://postgres:postgres@db:5432/mydatabase
    container_name: web
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydatabase
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  postgres_data:
